### PR TITLE
Add a function that adds a duotone effect to images

### PR DESCRIPTION
**Pull request by cjohansen**
Duotones are like grayscales, except with arbitrary from/to colors. See
https://duotones.co for examples.

### CODE REVIEW

**Comment by karls** [comment]
This is great! Many thanks for the PRs. 👏

**Comment by cjohansen** [comment]
Thanks @karls! Will you put a new version on Clojars as well?

**Comment by karls** [comment]
Yep, certainly. I think it'll be a couple of hours before I do that, though — I need to sit down and remind myself how to do it, but I'm in the middle of something atm. I'll ping you here when I've done it.

**Comment by karls** [comment]
Actually, it was easier than I thought. Unless I messed something up, 0.3.0 is on Clojars — https://clojars.org/fivetonine/collage.

Thanks again for the PRs!

**Comment by cjohansen** [comment]
Awesome, thanks for getting around to it so quickly!

**Pull request merged**
